// <auto-generated />
using System;
using CPR.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CPR.Infrastructure.Migrations
{
    [DbContext(typeof(CprDbContext))]
    [Migration("20260310000001_RefactorSkillAssessmentSchema")]
    partial class RefactorSkillAssessmentSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // BuildTargetModel is used for scaffolding new migrations.
            // MigrateAsync() uses the Up() method in the migration file directly.
            // The [Migration] attribute above is what enables EF Core to discover
            // and apply this migration.
#pragma warning restore 612, 618
        }
    }
}
