version: '3.8'

services:
  db_dev:
    image: postgres:15
    container_name: cpr_postgres_dev
    env_file: ../.env.dev
    restart: unless-stopped
    volumes:
      - db_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  db_test:
    image: postgres:15
    container_name: cpr_postgres_test
    env_file: ../.env.test
    restart: unless-stopped
    volumes:
      - db_data_test:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  db_data_dev:
  db_data_test:
