version: '3.8'

services:
  db:
    image: postgres:15
    container_name: cpr_postgres
    env_file: ../.env.dev
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: cpr_pgadmin
    env_file: ../.env.dev
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
