<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
  <PackageReference Include="Microsoft.Identity.Web" Version="3.3.1" />
  <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.0" />
  <PackageReference Include="Swashbuckle.AspNetCore.Filters" Version="9.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\\CPR.Application\\CPR.Application.csproj" />
    <ProjectReference Include="..\\CPR.Infrastructure\\CPR.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0" />
  <PackageReference Include="Hellang.Middleware.ProblemDetails" Version="6.4.0" />
  </ItemGroup>
</Project>
